---

# sudo apt -y install lsb-release apt-transport-https ca-certificates
- name: Add dependencies for PHP versions (Debian).
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
    state: present

# sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
- name: Add Ondrej Sury's apt key (Debian).
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

# echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php7.3.list
- name: Add Ondrej Sury's repo (Debian).
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
  register: php_ondrej_debian_repo

# sudo apt update
- name: Update apt caches after repo is added (Debian).
  apt: update_cache=true

- name: Intall php{{ php.version }}
  apt:
    name:
        - php{{ php.version }}
        - php{{ php.version }}-cli
    state: present

- name: Intall php{{ php.version }} extensions
  apt:
    name: php{{ php.version }}-{{ item }}
    state: present
  with_items:
    - json
    - pdo
    - mysql
    - zip
    - gd
    - mbstring
    - curl
    - xml
    - bcmath
    - opcache
    - intl